'use strict';

const SNAKE_COLOR = '#26ff00';
const FOOD_COLOR = '#ff8800';
const ULTRA_FOOD_COLOR = '#00fff7';
const GAME_WIDTH = 1600;
const GAME_HEIGHT = 900;
const CANVAS_WIDTH = 1600;
const CANVAS_HEIGHT = 900;
const SIMULATION_RATE = 20;
const RESOLUTION = 40;
const BACKGROUND_COLOR = 'black';
const CHECKER_COLOR = 'white';
module.exports = {
   CHECKER_COLOR,
   BACKGROUND_COLOR,
   SNAKE_COLOR,
   GAME_HEIGHT,
   GAME_WIDTH,
   SIMULATION_RATE,
   FOOD_COLOR,
   RESOLUTION,
   ULTRA_FOOD_COLOR,
   CANVAS_WIDTH,
   CANVAS_HEIGHT,
};
